(load "interpreter.scm")
(define test
  (lambda (file expected)
    (if (eq? (interpret file) expected) (string-append "Passed: " file) (string-append "Failed: " file))))

(with-handlers ([exn:fail? (lambda (exn) exn)])
    (test "TestsPart3/1.txt" 10))
(with-handlers ([exn:fail? (lambda (exn) exn)])
    (test "TestsPart3/2.txt" 14))
(with-handlers ([exn:fail? (lambda (exn) exn)])
    (test "TestsPart3/3.txt" 45))
(with-handlers ([exn:fail? (lambda (exn) exn)])
    (test "TestsPart3/4.txt" 55))
(with-handlers ([exn:fail? (lambda (exn) exn)])
    (test "TestsPart3/5.txt" 1))
(with-handlers ([exn:fail? (lambda (exn) exn)])
    (test "TestsPart3/6.txt" 115))
(with-handlers ([exn:fail? (lambda (exn) exn)])
    (test "TestsPart3/7.txt" 'true))
(with-handlers ([exn:fail? (lambda (exn) exn)])
    (test "TestsPart3/8.txt" 20))
(with-handlers ([exn:fail? (lambda (exn) exn)])
    (test "TestsPart3/9.txt" 24))
(with-handlers ([exn:fail? (lambda (exn) exn)])
    (test "TestsPart3/10.txt" 2))
(with-handlers ([exn:fail? (lambda (exn) exn)])
    (test "TestsPart3/11.txt" 35))
(with-handlers ([exn:fail? (lambda (exn) exn)])
    (test "TestsPart3/12.txt" 20)) ;Should give error
(with-handlers ([exn:fail? (lambda (exn) exn)])
    (test "TestsPart3/13.txt" 90))
(with-handlers ([exn:fail? (lambda (exn) exn)])
    (test "TestsPart3/14.txt" 69))
(with-handlers ([exn:fail? (lambda (exn) exn)])
    (test "TestsPart3/15.txt" 87))
(with-handlers ([exn:fail? (lambda (exn) exn)])
    (test "TestsPart3/16.txt" 64))
(with-handlers ([exn:fail? (lambda (exn) exn)])
    (test "TestsPart3/17.txt" 20)) ;Should give error
(with-handlers ([exn:fail? (lambda (exn) exn)])
    (test "TestsPart3/18.txt" 125))
(with-handlers ([exn:fail? (lambda (exn) exn)])
    (test "TestsPart3/19.txt" 100))
(with-handlers ([exn:fail? (lambda (exn) exn)])
    (test "TestsPart3/20.txt" 2000400))